// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Xzs525KOVwgUiOYoi8YOD8EVTkkdM4s',
    appId: '1:539026808165:web:17c963f1e3a8e7d1e6158c',
    messagingSenderId: '539026808165',
    projectId: 'buzzchat-fabc2',
    authDomain: 'buzzchat-fabc2.firebaseapp.com',
    storageBucket: 'buzzchat-fabc2.appspot.com',
    measurementId: 'G-JYEESTN91C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaBsIM__HoRtVTMciCX9AolgvfgNrrNM',
    appId: '1:539026808165:android:4abab24dc0d105d6e6158c',
    messagingSenderId: '539026808165',
    projectId: 'buzzchat-fabc2',
    storageBucket: 'buzzchat-fabc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2LoDWspi2sxjQvxAd6B4eB5pB_3QvLE',
    appId: '1:539026808165:ios:262a935101418486e6158c',
    messagingSenderId: '539026808165',
    projectId: 'buzzchat-fabc2',
    storageBucket: 'buzzchat-fabc2.appspot.com',
    iosBundleId: 'com.example.buzzChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2LoDWspi2sxjQvxAd6B4eB5pB_3QvLE',
    appId: '1:539026808165:ios:262a935101418486e6158c',
    messagingSenderId: '539026808165',
    projectId: 'buzzchat-fabc2',
    storageBucket: 'buzzchat-fabc2.appspot.com',
    iosBundleId: 'com.example.buzzChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Xzs525KOVwgUiOYoi8YOD8EVTkkdM4s',
    appId: '1:539026808165:web:fd11be547160dcb1e6158c',
    messagingSenderId: '539026808165',
    projectId: 'buzzchat-fabc2',
    authDomain: 'buzzchat-fabc2.firebaseapp.com',
    storageBucket: 'buzzchat-fabc2.appspot.com',
    measurementId: 'G-JZZK95ZD3Y',
  );

}